FROM chialab/php:7.4-apache

# create non-root user
RUN useradd --create-home --shell /bin/bash --uid 1000 user

# init xdebug
RUN echo "xdebug.remote_enable=on" >> /usr/local/etc/php/conf.d/xdebug.ini && echo "xdebug.remote_autostart=off" >> /usr/local/etc/php/conf.d/xdebug.ini

# RUN echo 'extension=pdo_pgsql' >> /usr/local/etc/php/conf.d/php.ini && echo 'extension=pgsql' >> /usr/local/etc/php/conf.d/php.ini

RUN apt-get update && apt-get install -y libc-client-dev libkrb5-dev && rm -r /var/lib/apt/lists/*
RUN docker-php-ext-configure imap --with-kerberos --with-imap-ssl \
    && docker-php-ext-install imap

# Update composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# create cache directories for composer
RUN mkdir /.composer && chmod 777 -R /.composer
