version: '3'

services:
  code:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./apache.conf:/etc/apache2/sites-available/000-default.conf
      - ./src:/var/www/html
    ports:
      - 8080:80
    links:
      - database
    environment:
      XDEBUG_CONFIG: remote_host=172.17.0.1
      PHP_IDE_CONFIG: "serverName=development"
      XDEBUG_MODE: debug

  database:
    image: postgres:latest
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=secret

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"